version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_test
    ports:
      - "5432:5432"

  quarkus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quarkus-app
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/my_test
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: >
      sh -c "java $JAVA_OPTS -jar /app/quarkus-run.jar"
