# task-build-image.yml
---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: docker
inputs:
- name: git-sources
outputs:
- name: image
params:
  CONTEXT: git-sources/Dockerfile
  BUILD_ARG_QUARKUS_PROFILE: ""
  BUILD_ARG_APP_NAME: ""
run:
  path: build
  args:
    - --build-arg
    - QUARKUS_PROFILE=${BUILD_ARG_QUARKUS_PROFILE}
    - --build-arg
    - APP_NAME=${BUILD_ARG_APP_NAME}
    - -t
    - $(cat /tmp/build/put/image/digest)
    - ${CONTEXT}

