version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: concourse
    networks: 
      - concourse-net

  concourse-web:
    image: concourse/concourse
    command: web
    depends_on: [concourse-db]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: concourse
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_ADD_LOCAL_USER: test:test
    ports:
      - "8080:8080"
    networks: 
      - concourse-net

  concourse-worker:
    image: concourse/concourse
    command: worker
    depends_on: [concourse-web]
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
    privileged: true
    networks: 
      - concourse-net

networks:
  concourse-net:
